[project]
name = "cutaway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy<2",
    "chromadb==1.0.0",
    "opencv-python==4.11.0.86",
    "imagebind @ git+https://github.com/facebookresearch/ImageBind.git",
]
